# Generated by Django 4.0.3 on 2022-04-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acidic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='bold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='pairing',
            field=models.ManyToManyField(through='products.ProductPairing', to='products.pairing'),
        ),
        migrations.AddField(
            model_name='product',
            name='sweet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='tannic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
