# Generated by Django 4.0.3 on 2022-04-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_acidic_product_bold_product_pairing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='acidic',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='bold',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='sweet',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='tannic',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
