# Generated by Django 4.0.3 on 2022-04-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_acidic_alter_product_bold_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pairing',
            new_name='pairings',
        ),
    ]
