# Generated by Django 4.0.3 on 2022-04-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_pairing_product_pairings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='grapes',
            new_name='grape',
        ),
    ]
