# Generated by Django 4.0.3 on 2022-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_grapes_product_grape'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='image_url',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
